package com.vishal.payflo.advice.enums;

public enum ErrorCode {
    PAYMENT_TRANSACTION_NOT_FOUND,
    METHOD_ARGUMENT_TYPE_MISMATCH,
    VPA_SEPARATOR_COUNT_MISMATCH,
    VPA_INVALID_IDENTIFIER_FORMAT,
    VPA_INVALID_PAYMENT_SERVICE_PROVIDER_FORMAT,
    VPA_UNKNOWN_PAYMENT_SERVICE_PROVIDER,
    INVALID_CARD_NUMBER_FORMAT,
    INVALID_CARD_NUMBER,
    EXPIRED_CARD,
    INVALID_CVV_FORMAT,
    INVALID_REQUEST_BODY_FORMAT
}
