package com.vishal.payflo.kafka.topics;

public enum KafkaTopic {
    PAYMENT_INITIATED,
    PAYMENT_INITIATED_NOTIFICATION,
    PAYMENT_RECEIVED,
    PAYMENT_COMPLETED_NOTIFICATION,
    PAYMENT_FAILED,
    PAYMENT_FAILED_NOTIFICATION,
    PAYMENT_TIMED_OUT,
    PAYMENT_TIMED_OUT_NOTIFICATION,
    DLT
}